name: Node.js Bot

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' # تم التحديث إلى نسخة 20
        
    - name: Install dependencies
      run: npm ci # استخدام npm ci بدلاً من npm install لضمان تثبيت نظيف
        
    - name: Run Bot
      run: npm start
